In [1]:
import pandas as pd
from pathlib import Path
import numpy as np

In [2]:
# Path to the csv
DATA_PATH   = Path('/media/haupert/data/mes_projets/05_xprize/performance')

# list of csv
CSV_LIST    = [
            'XP_final_annotations - rec1dmu.csv',
            'XP_final_annotations - rec3dmu.csv',
            'XP_final_annotations - rec3dmu_v2.csv',
            'XP_final_annotations - rec4dmu.csv',
            'XP_final_annotations - rec4dmu_v2.csv',
            'XP_final_annotations - rec6dmu.csv',
            'XP_final_annotations - rec7dmu.csv',
            ]

In [3]:
# Load data in the CSV_LIST
df = pd.DataFrame()
for csv in CSV_LIST:
    df_tempo = pd.read_csv(DATA_PATH / csv)
    # Add the name of the file in the dataframe to keep track of the site
    # keep only the name of the file after the last '-' and before the '.csv'
    df_tempo['site'] = csv.split(' - ')[1].split('.csv')[0]
    df = pd.concat([df, df_tempo], axis=0)

# lower case all strings
df= df.map(lambda s:s.lower() if type(s) == str else s)

# display the total number of clusters per site
display(df.groupby('site')['cluster_number'].nunique())

# # display
# display(df)

# # for each site, keep only the cluster_number where all validator_name are different from 0
# df2 = pd.DataFrame()
# for site in df['site'].unique():
#     df2 = pd.concat([df2, df.loc[df['site'] == site].groupby('cluster_number').filter(lambda x: (x['validated_specie'] != '0').all() and (x['validated_specie'] != 0).all() and (x['validated_specie'] != np.nan).all())], axis=0)

# # display
# display(df2)

#  keep the rows where validated_specie is different from 0 and '0'
df3 = pd.DataFrame()
df3 = df.loc[(df['validated_specie'] != '0') & (df['validated_specie'] != 0) & (df['validated_specie'] != np.nan)]

# remove validator_name with '0' and nan
df3 = df3.loc[(df3['validator_name'] != '0') & (df3['validator_name'] is not None)]

# test if the validated_specie is a string if not, remove the row
df3 = df3.loc[df3['validated_specie'].map(lambda x: type(x) == str)]

# in the validated_specie column
# keep the first string before the ',' if any
df3['validated_specie'] = df3['validated_specie'].map(lambda x: x.split(',')[0] if ',' in x else x)
# keep the first string before the '/' if any
df3['validated_specie'] = df3['validated_specie'].map(lambda x: x.split('/')[0] if '/' in x else x)
# keep the first string before the '-' if any   
df3['validated_specie'] = df3['validated_specie'].map(lambda x: x.split('-')[0] if '-' in x else x)
# keep the first string before the '_' if any
df3['validated_specie'] = df3['validated_specie'].map(lambda x: x.split('_')[0] if '_' in x else x)

# display
display(df3)

# display unique validated_specie
display(df3['validated_specie'].unique())

# display the number of unique validated_specie
print(f'the number of validated specie is {len(df3["validated_specie"].unique())}')

site
rec1dmu        67
rec3dmu        25
rec3dmu_v2     54
rec4dmu       143
rec4dmu_v2     38
rec6dmu       103
rec7dmu        49
Name: cluster_number, dtype: int64

,cluster_number,filename_ts,period,suggested_class,suggested_label,validated_class,validated_specie,validator_name,comment,site
12,0,20240721_003200_12.wav,1. night,aves,platyrinchus coronatus_golden-crowned spadebill,amphibia,boana cinerascens,pedro taucce,muito ruido,rec1dmu
13,0,20240721_003200_13.wav,1. night,aves,platyrinchus coronatus_golden-crowned spadebill,amphibia,boana cinerascens,pedro taucce,muito ruido,rec1dmu
14,0,20240721_003200_14.wav,1. night,aves,platyrinchus coronatus_golden-crowned spadebill,amphibia,boana cinerascens,pedro taucce,muito ruido,rec1dmu
15,0,20240721_003200_15.wav,1. night,aves,platyrinchus coronatus_golden-crowned spadebill,amphibia,boana cinerascens,pedro taucce,muito ruido,rec1dmu
19,0,20240721_013600_19.wav,1. night,aves,platyrinchus coronatus_golden-crowned spadebill,"amphibia, aves",boana cinerascens,pedro taucce,bacurau cantando entre 9 e 9.5 s. nyctidromus ...,rec1dmu
...,...,...,...,...,...,...,...,...,...,...
1964,9004,rec7dmu_20240721_073230_1964.wav,2. dawn,aves,bubo virginianus_great horned owl,aves,lipaugus vociferans,mario,NaN,rec7dmu
1965,9004,rec7dmu_20240721_074000_1965.wav,2. dawn,aves,ibycter americanus_red-throated caracara,aves,lipaugus vociferans,mario,NaN,rec7dmu
1968,9004,rec7dmu_20240721_082230_1968.wav,2. dawn,aves,trogon melanurus_black-tailed trogon,amphibia,scinax sp. nov.,gordo,NaN,rec7dmu
1969,9004,rec7dmu_20240721_085230_1969.wav,2. dawn,aves,nyctibius griseus_common potoo,aves,lipaugus vociferans,mario,NaN,rec7dmu
1970,9004,rec7dmu_20240721_085230_1970.wav,2. dawn,aves,lipaugus vociferans_screaming piha,aves,lipaugus vociferans,mario,NaN,rec7dmu

array(['boana cinerascens', 'bacurau', 'orthoptera', 'ornithion inerme',
       'percnostola minor', 'brotogeris chrysoptera',
       'hypocnemis peruviana', 'scinax ruber', 'nyctidromus albicollis',
       'antrostoma rufus', 'noise', 'antrostomus rufus',
       'lipaugus vociferans', 'pulsatrix perspicillata', 'no detection',
       'sittasomus griseicapillus', 'cicadidae morfo sp', 'homo sapiens',
       'drone', 'crypturellus cinereus', 'ramphastos tucanus',
       'crotophaga ani', 'cacicus cela', 'chiroxiphia regina',
       'xipholena punicea', 'amazona amazonica', 'hylocharis sapphirina',
       'lipaugus', 'trachycephalus cunauaru', 'rhytipterna simplex',
       'patagioenas plumbea', 'crypturellus variegatus', 'tinamus major',
       'pachysylvia hypoxantha', 'herpsilochmus dorsimaculatus',
       'hypocnemis hypoxantha', 'lipaugus ', 'trogon viridis',
       'especies repetidas', 'dendrocolaptes radiolatus',
       'ramphastos vitellinus', 'hemitriccus zosterops',
       'ramphastos tucanos', 'boana cf. lanciformis', 'rhinella marina',
       'scinax cf. ruber', 'ramphotrigon ruficauda', 'anaxipha sp.3',
       'orthoptera ', 'monasa', 'scinax sp. nov.', 'scinax cruentomma',
       'ruido', 'pauxi tuberosa', 'xiphorhynchus beauperthuysii',
       'lophostrix cristata', 'micrastur semitorquatus', 'megascops usta',
       'odontophorus gujanensis', 'amazona farinosa',
       'nyctiprogne leucopyga latifascia'], dtype=object)

the number of validated specie is 61

In [8]:
from sklearn.metrics.cluster import adjusted_mutual_info_score, adjusted_rand_score, normalized_mutual_info_score
from sklearn.metrics import v_measure_score, homogeneity_score, completeness_score

# add a column predicted_label which is the sum of cluster_number 
df3['predicted_label'] = df3['cluster_number'] 

# # convert period to integer when night -> 10000, dawn -> 20000, day -> 30000, duk -> 40000
# df3['period_int'] = df3['period'].map(lambda x: 10000 if x == '1. night' else 20000 if x == '2. dawn' else 30000 if x == '3. day' else 40000 if x == '4. dusk' else x)

# # add a column predicted_label which is the sum of cluster_number and period_int
# df3['predicted_label'] = df3['cluster_number'] + df3['period_int']

# transform the validated_specie into integer via a dictionary
species = df3['validated_specie'].unique()
species = species[species != '0']
species = species[species != 0]
species = species[species != np.nan]
species = species[species != 'nan']

# create a dictionary to transform the validated_specie into integer
species_dict = {species[i]: i for i in range(len(species))}
df3['true_label'] = df3['validated_specie'].map(species_dict)

# display
display(df3)

# compute the adjusted_mutual_info_score and adjusted_rand_score
ami = adjusted_mutual_info_score(df3['true_label'], df3['predicted_label'])
ari = adjusted_rand_score(df3['true_label'], df3['predicted_label'])
homogeneity = homogeneity_score(df3['true_label'], df3['predicted_label'])
completeness = completeness_score(df3['true_label'], df3['predicted_label'])
vmeasure = v_measure_score(df3['true_label'], df3['predicted_label'])
nmi = normalized_mutual_info_score(df3['true_label'], df3['predicted_label'])


print(f'adjusted_mutual_info_score: {ami}')
print(f'adjusted_rand_score: {ari}')
print(f'normalized_mutual_info_score: {nmi}')
print(f'homogeneity_score: {homogeneity}')
print(f'completeness_score: {completeness}')
print(f'v_measure_score: {vmeasure}')

,cluster_number,filename_ts,period,suggested_class,suggested_label,validated_class,validated_specie,validator_name,comment,site,predicted_label,true_label
12,0,20240721_003200_12.wav,1. night,aves,platyrinchus coronatus_golden-crowned spadebill,amphibia,boana cinerascens,pedro taucce,muito ruido,rec1dmu,0,0
13,0,20240721_003200_13.wav,1. night,aves,platyrinchus coronatus_golden-crowned spadebill,amphibia,boana cinerascens,pedro taucce,muito ruido,rec1dmu,0,0
14,0,20240721_003200_14.wav,1. night,aves,platyrinchus coronatus_golden-crowned spadebill,amphibia,boana cinerascens,pedro taucce,muito ruido,rec1dmu,0,0
15,0,20240721_003200_15.wav,1. night,aves,platyrinchus coronatus_golden-crowned spadebill,amphibia,boana cinerascens,pedro taucce,muito ruido,rec1dmu,0,0
19,0,20240721_013600_19.wav,1. night,aves,platyrinchus coronatus_golden-crowned spadebill,"amphibia, aves",boana cinerascens,pedro taucce,bacurau cantando entre 9 e 9.5 s. nyctidromus ...,rec1dmu,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1964,9004,rec7dmu_20240721_073230_1964.wav,2. dawn,aves,bubo virginianus_great horned owl,aves,lipaugus vociferans,mario,NaN,rec7dmu,9004,12
1965,9004,rec7dmu_20240721_074000_1965.wav,2. dawn,aves,ibycter americanus_red-throated caracara,aves,lipaugus vociferans,mario,NaN,rec7dmu,9004,12
1968,9004,rec7dmu_20240721_082230_1968.wav,2. dawn,aves,trogon melanurus_black-tailed trogon,amphibia,scinax sp. nov.,gordo,NaN,rec7dmu,9004,50
1969,9004,rec7dmu_20240721_085230_1969.wav,2. dawn,aves,nyctibius griseus_common potoo,aves,lipaugus vociferans,mario,NaN,rec7dmu,9004,12
1970,9004,rec7dmu_20240721_085230_1970.wav,2. dawn,aves,lipaugus vociferans_screaming piha,aves,lipaugus vociferans,mario,NaN,rec7dmu,9004,12

adjusted_mutual_info_score: 0.5281925754147323
adjusted_rand_score: 0.12952618280174064
normalized_mutual_info_score: 0.5833525871070061
homogeneity_score: 0.720265821917084
completeness_score: 0.49017638417853215
v_measure_score: 0.5833525871070061

In [226]:
# get the species name associated with the integer value in the dictionary species_dict
species_dict = {v: k for k, v in species_dict.items()}

# display the number of clusters annotated over all sites vs the totalnumber of clusters 
print(f'The total number of clusters that were annotated over all sites is: {len(df3["predicted_label"].unique())} / {df.groupby("site")["cluster_number"].nunique().sum()}')

# display the number of clusters per site
for site in df3['site'].unique():
    print(f'The total number of clusters that were annotated in {site} is: {len(df3.loc[df3["site"] == site, "predicted_label"].unique())} / {df.loc[df["site"] == site, "cluster_number"].nunique()}')

The total number of clusters that were annotated over all sites is: 52 / 479
The total number of clusters that were annotated in rec1dmu is: 6 / 67
The total number of clusters that were annotated in rec3dmu is: 16 / 25
The total number of clusters that were annotated in rec4dmu is: 21 / 143
The total number of clusters that were annotated in rec4dmu_v2 is: 4 / 38
The total number of clusters that were annotated in rec6dmu is: 28 / 103
The total number of clusters that were annotated in rec7dmu is: 12 / 49

In [227]:
# For each cluster, print the species with the number of points per species
for pseudo_label_id in df3['predicted_label'].unique() :
    if pseudo_label_id != -1 :
        print(f'Cluster {pseudo_label_id} :')
        for true_label_id in df3['true_label'].unique() :
            if np.sum((df3['predicted_label'] == pseudo_label_id) & (df3['true_label'] == true_label_id)) > 0:
                print(f'    {species_dict[true_label_id]} : {np.sum((df3["predicted_label"] == pseudo_label_id) & (df3["true_label"] == true_label_id))}')

Cluster 0 :
    boana cinerascens : 22
    bacurau : 1
    orthoptera : 16
    ornithion inerme : 1
    percnostola minor : 1
    brotogeris chrysoptera : 2
    hypocnemis peruviana : 1
    antrostomus rufus : 7
    lipaugus vociferans : 1
    no detection : 49
    sittasomus griseicapillus : 1
    pachysylvia hypoxantha : 30
Cluster 2 :
    orthoptera : 25
    scinax ruber : 8
    nyctidromus albicollis : 2
    antrostoma rufus : 2
    lipaugus vociferans : 3
    trachycephalus cunauaru : 42
    patagioenas plumbea : 1
    pachysylvia hypoxantha : 30
    ramphotrigon ruficauda : 1
    scinax cruentomma : 1
Cluster 3 :
    boana cinerascens : 2
    orthoptera : 19
    nyctidromus albicollis : 2
    noise : 6
    antrostomus rufus : 16
    lipaugus vociferans : 38
    trachycephalus cunauaru : 1
    crypturellus variegatus : 2
    tinamus major : 1
    pachysylvia hypoxantha : 1
    herpsilochmus dorsimaculatus : 3
    hypocnemis hypoxantha : 1
    ramphastos vitellinus : 2
Cluster 5 :
    noise : 48
    lipaugus vociferans : 1
Cluster 9 :
    nyctidromus albicollis : 1
    antrostomus rufus : 27
    lipaugus vociferans : 1
    no detection : 3
    cicadidae morfo sp : 13
Cluster 13 :
    pulsatrix perspicillata : 1
Cluster 1 :
    boana cinerascens : 23
    no detection : 21
    sittasomus griseicapillus : 1
    trachycephalus cunauaru : 4
    rhytipterna simplex : 1
    boana cf. lanciformis : 1
    rhinella marina : 1
    scinax cf. ruber : 6
    scinax sp. nov. : 7
Cluster 4 :
    lipaugus vociferans : 1
    cicadidae morfo sp : 2
    patagioenas plumbea : 22
    herpsilochmus dorsimaculatus : 4
    lipaugus  : 1
    trogon viridis : 1
Cluster 6 :
    noise : 8
    lipaugus vociferans : 1
    homo sapiens : 4
    drone : 4
    crypturellus cinereus : 1
    ramphastos tucanus : 1
    crotophaga ani : 1
    cacicus cela : 3
    chiroxiphia regina : 1
    xipholena punicea : 5
    amazona amazonica : 1
    rhytipterna simplex : 1
    especies repetidas : 49
Cluster 7 :
    cicadidae morfo sp : 11
    trachycephalus cunauaru : 35
Cluster 8 :
    no detection : 5
    cicadidae morfo sp : 1
    hylocharis sapphirina : 1
    trachycephalus cunauaru : 44
Cluster 16 :
    lipaugus vociferans : 5
    ruido : 4
Cluster 18 :
    lipaugus vociferans : 1
    lipaugus : 1
    rhytipterna simplex : 3
    pauxi tuberosa : 4
    xiphorhynchus beauperthuysii : 1
Cluster 9000 :
    noise : 6
    lipaugus vociferans : 23
    trachycephalus cunauaru : 5
Cluster 9001 :
    noise : 11
Cluster 9003 :
    noise : 1
Cluster 9004 :
    noise : 11
    lipaugus vociferans : 5
    scinax sp. nov. : 2
    micrastur semitorquatus : 1
    megascops usta : 1
    odontophorus gujanensis : 1
    amazona farinosa : 1
    nyctiprogne leucopyga latifascia : 1
Cluster 9005 :
    noise : 28
Cluster 12 :
    lipaugus vociferans : 1
    trachycephalus cunauaru : 16
    crypturellus variegatus : 1
Cluster 14 :
    noise : 1
    herpsilochmus dorsimaculatus : 12
    hemitriccus zosterops : 1
    ramphastos tucanos : 1
Cluster 17 :
    trachycephalus cunauaru : 29
    dendrocolaptes radiolatus : 1
    anaxipha sp.3 : 1
Cluster 24 :
    orthoptera : 45
Cluster 25 :
    orthoptera : 50
Cluster 26 :
    orthoptera : 37
Cluster 50 :
    orthoptera : 50
Cluster 51 :
    orthoptera : 20
Cluster 52 :
    orthoptera : 50
Cluster 53 :
    orthoptera : 50
Cluster 54 :
    no detection : 1
Cluster 11 :
    boana cinerascens : 1
    trachycephalus cunauaru : 35
    rhytipterna simplex : 50
Cluster 21 :
    nyctidromus albicollis : 49
    micrastur semitorquatus : 1
Cluster 22 :
    no detection : 21
Cluster 28 :
    orthoptera  : 5
Cluster 32 :
    monasa : 2
Cluster 33 :
    trachycephalus cunauaru : 7
Cluster 34 :
    orthoptera : 18
Cluster 35 :
    orthoptera : 29
Cluster 36 :
    orthoptera : 22
Cluster 37 :
    orthoptera : 9
Cluster 38 :
    orthoptera : 16
Cluster 39 :
    orthoptera : 5
Cluster 40 :
    orthoptera : 8
Cluster 41 :
    orthoptera : 8
Cluster 42 :
    orthoptera : 19
Cluster 43 :
    boana cinerascens : 14
Cluster 44 :
    orthoptera : 14
Cluster 45 :
    orthoptera : 29
Cluster 46 :
    orthoptera : 18
Cluster 47 :
    orthoptera : 11
Cluster 49 :
    orthoptera : 13
Cluster 20 :
    lophostrix cristata : 2
Cluster 23 :
    lipaugus vociferans : 42

In [172]:
# list of labels corresponding to the most represented species in each cluster
label_to_cluster = []

# For each cluster, select the species with the most points and compute the percentage of points in the cluster
for pseudo_label_id in df3['predicted_label'].unique() :
    if pseudo_label_id != -1 :
        label_to_cluster += [df3['true_label'].unique()[np.argmax([np.sum((df3['predicted_label'] == pseudo_label_id) & (df3['true_label'] == true_label_id)) for true_label_id in np.unique(df3['true_label'])])]]
        print(f'Cluster {pseudo_label_id} : {species_dict[label_to_cluster[-1]]} : {np.round(np.sum((df3["predicted_label"] == pseudo_label_id) & (df3["true_label"] == label_to_cluster[-1])) / np.sum(df3["predicted_label"] == pseudo_label_id) * 100).astype("int")}%')

Cluster 0 : no detection : 37%
Cluster 2 : trachycephalus cunauaru : 37%
Cluster 3 : lipaugus vociferans : 40%
Cluster 5 : noise : 98%
Cluster 9 : antrostomus rufus : 60%
Cluster 13 : pulsatrix perspicillata : 100%
Cluster 1 : boana cinerascens : 35%
Cluster 4 : patagioenas plumbea : 71%
Cluster 6 : especies repetidas : 61%
Cluster 7 : trachycephalus cunauaru : 76%
Cluster 8 : trachycephalus cunauaru : 86%
Cluster 16 : lipaugus vociferans : 56%
Cluster 18 : pauxi tuberosa : 40%
Cluster 9000 : lipaugus vociferans : 68%
Cluster 9001 : noise : 100%
Cluster 9003 : noise : 100%
Cluster 9004 : noise : 48%
Cluster 9005 : noise : 100%
Cluster 12 : trachycephalus cunauaru : 89%
Cluster 14 : herpsilochmus dorsimaculatus : 80%
Cluster 17 : trachycephalus cunauaru : 94%
Cluster 24 : orthoptera : 100%
Cluster 25 : orthoptera : 100%
Cluster 26 : orthoptera : 100%
Cluster 50 : orthoptera : 100%
Cluster 51 : orthoptera : 100%
Cluster 52 : orthoptera : 100%
Cluster 53 : orthoptera : 100%
Cluster 54 : no detection : 100%
Cluster 11 : rhytipterna simplex : 58%
Cluster 21 : nyctidromus albicollis : 98%
Cluster 22 : no detection : 100%
Cluster 28 : orthoptera  : 100%
Cluster 32 : monasa : 100%
Cluster 33 : trachycephalus cunauaru : 100%
Cluster 34 : orthoptera : 100%
Cluster 35 : orthoptera : 100%
Cluster 36 : orthoptera : 100%
Cluster 37 : orthoptera : 100%
Cluster 38 : orthoptera : 100%
Cluster 39 : orthoptera : 100%
Cluster 40 : orthoptera : 100%
Cluster 41 : orthoptera : 100%
Cluster 42 : orthoptera : 100%
Cluster 43 : boana cinerascens : 100%
Cluster 44 : orthoptera : 100%
Cluster 45 : orthoptera : 100%
Cluster 46 : orthoptera : 100%
Cluster 47 : orthoptera : 100%
Cluster 49 : orthoptera : 100%
Cluster 20 : lophostrix cristata : 100%
Cluster 23 : lipaugus vociferans : 100%

In [173]:
# list of species that are not the most represented in any cluster
missing_species_as_main_cluster = np.setdiff1d(df3['true_label'].unique(), label_to_cluster)

print(f'{len(missing_species_as_main_cluster)} / {len(species_dict)} species are not representing by a cluster.')

print("The list is:")
for label in missing_species_as_main_cluster :
    print(f'    {species_dict[label]}')

44 / 61 species are not representing by a cluster.
The list is:
    bacurau
    ornithion inerme
    percnostola minor
    brotogeris chrysoptera
    hypocnemis peruviana
    scinax ruber
    antrostoma rufus
    sittasomus griseicapillus
    cicadidae morfo sp
    homo sapiens
    drone
    crypturellus cinereus
    ramphastos tucanus
    crotophaga ani
    cacicus cela
    chiroxiphia regina
    xipholena punicea
    amazona amazonica
    hylocharis sapphirina
    lipaugus
    crypturellus variegatus
    tinamus major
    pachysylvia hypoxantha
    hypocnemis hypoxantha
    lipaugus
    trogon viridis
    dendrocolaptes radiolatus
    ramphastos vitellinus
    hemitriccus zosterops
    ramphastos tucanos
    boana cf. lanciformis
    rhinella marina
    scinax cf. ruber
    ramphotrigon ruficauda
    anaxipha sp.3
    scinax sp. nov.
    scinax cruentomma
    ruido
    xiphorhynchus beauperthuysii
    micrastur semitorquatus
    megascops usta
    odontophorus gujanensis
    amazona farinosa
    nyctiprogne leucopyga latifascia

In [181]:
# for each species in the list missing_species_as_main_cluster, find the clusters where they are present
# and the percentage of points that they represent from the total number of points of the species
for label in missing_species_as_main_cluster :
    print(f'{species_dict[label]} :')
    for pseudo_label_id in np.unique(df3['predicted_label']) :
        if pseudo_label_id != -1 :
            if np.sum((df3['predicted_label'] == pseudo_label_id) & (df3['true_label'] == label)) > 0:
                print(f'    Cluster {pseudo_label_id} : {np.round(np.sum((df3["predicted_label"] == pseudo_label_id) & (df3["true_label"] == label)) / np.sum(df3["true_label"] == label) * 100).astype("int")}%')
    # print the sum of the percentage of points that the species represent in the clusters
    print(f'    Total : {np.round(np.sum([np.sum((df3["predicted_label"] == pseudo_label_id) & (df3["true_label"] == label)) / np.sum(df3["true_label"] == label) * 100 for pseudo_label_id in df3["predicted_label"].unique() if pseudo_label_id != -1])).astype("int")}%')

bacurau :
    Cluster 0 : 100%
    Total : 100%
ornithion inerme :
    Cluster 0 : 100%
    Total : 100%
percnostola minor :
    Cluster 0 : 100%
    Total : 100%
brotogeris chrysoptera :
    Cluster 0 : 100%
    Total : 100%
hypocnemis peruviana :
    Cluster 0 : 100%
    Total : 100%
scinax ruber :
    Cluster 2 : 100%
    Total : 100%
antrostoma rufus :
    Cluster 2 : 100%
    Total : 100%
sittasomus griseicapillus :
    Cluster 0 : 50%
    Cluster 1 : 50%
    Total : 100%
cicadidae morfo sp :
    Cluster 4 : 7%
    Cluster 7 : 41%
    Cluster 8 : 4%
    Cluster 9 : 48%
    Total : 100%
homo sapiens :
    Cluster 6 : 100%
    Total : 100%
drone :
    Cluster 6 : 100%
    Total : 100%
crypturellus cinereus :
    Cluster 6 : 100%
    Total : 100%
ramphastos tucanus :
    Cluster 6 : 100%
    Total : 100%
crotophaga ani :
    Cluster 6 : 100%
    Total : 100%
cacicus cela :
    Cluster 6 : 100%
    Total : 100%
chiroxiphia regina :
    Cluster 6 : 100%
    Total : 100%
xipholena punicea :
    Cluster 6 : 100%
    Total : 100%
amazona amazonica :
    Cluster 6 : 100%
    Total : 100%
hylocharis sapphirina :
    Cluster 8 : 100%
    Total : 100%
lipaugus :
    Cluster 18 : 100%
    Total : 100%
crypturellus variegatus :
    Cluster 3 : 67%
    Cluster 12 : 33%
    Total : 100%
tinamus major :
    Cluster 3 : 100%
    Total : 100%
pachysylvia hypoxantha :
    Cluster 0 : 49%
    Cluster 2 : 49%
    Cluster 3 : 2%
    Total : 100%
hypocnemis hypoxantha :
    Cluster 3 : 100%
    Total : 100%
lipaugus  :
    Cluster 4 : 100%
    Total : 100%
trogon viridis :
    Cluster 4 : 100%
    Total : 100%
dendrocolaptes radiolatus :
    Cluster 17 : 100%
    Total : 100%
ramphastos vitellinus :
    Cluster 3 : 100%
    Total : 100%
hemitriccus zosterops :
    Cluster 14 : 100%
    Total : 100%
ramphastos tucanos :
    Cluster 14 : 100%
    Total : 100%
boana cf. lanciformis :
    Cluster 1 : 100%
    Total : 100%
rhinella marina :
    Cluster 1 : 100%
    Total : 100%
scinax cf. ruber :
    Cluster 1 : 100%
    Total : 100%
ramphotrigon ruficauda :
    Cluster 2 : 100%
    Total : 100%
anaxipha sp.3 :
    Cluster 17 : 100%
    Total : 100%
scinax sp. nov. :
    Cluster 1 : 78%
    Cluster 9004 : 22%
    Total : 100%
scinax cruentomma :
    Cluster 2 : 100%
    Total : 100%
ruido :
    Cluster 16 : 100%
    Total : 100%
xiphorhynchus beauperthuysii :
    Cluster 18 : 100%
    Total : 100%
micrastur semitorquatus :
    Cluster 21 : 50%
    Cluster 9004 : 50%
    Total : 100%
megascops usta :
    Cluster 9004 : 100%
    Total : 100%
odontophorus gujanensis :
    Cluster 9004 : 100%
    Total : 100%
amazona farinosa :
    Cluster 9004 : 100%
    Total : 100%
nyctiprogne leucopyga latifascia :
    Cluster 9004 : 100%
    Total : 100%